### ISSUE TITLE
Unable to login in iOS app

### ISSUE THREAD

**Issue by michaelgodshall** [productiveme/accounts-asana#1]
I tried running my meteor app as an iOS app (in the iOS simulator as described here: https://www.meteor.com/try/7 ), but I can't get the Asana login to work.  Clicking the login button opens the Asana login page, but after logging in it never redirects to the app.  Instead, it shows a page with the following message: "Login completed. Click here to close this window".  However, clicking the link does not close the window, and returning to the app still shows me as not logged in.  I even tried switching from popup to redirect flow (recommended here: https://github.com/meteor/meteor/wiki/OAuth-for-mobile-Meteor-clients#popup-versus-redirect-flow), but it doesn't seem to change the behavior.  Any thoughts on how to solve this?

**Comment by productiveme** [comment]
Some changes are required to the asana package this depends on, I'm busy testing those now.

**Comment by productiveme** [comment]
I've updated the packages to enable redirect flow, the new version depends on meteor 1.0 and so I've bumped the version to 1.0.0.
